shared:
  image: node:18
  environment:
    GIT_SHALLOW_CLONE_SINGLE_BRANCH: true
  steps:
    - diff: git diff HEAD..HEAD^
    - count: git rev-list --count HEAD

jobs:
  main:
    requires: [ ~commit ]

  releaseJob:
    requires: [ ~release ]

  tagJob:
    requires: [ ~tag ]

  releaseJobDepth3:
    requires: [ ~release ]
    environment:
      GIT_SHALLOW_CLONE_DEPTH: 3

  tagJobDepth3:
    requires: [ ~tag ]
    environment:
      GIT_SHALLOW_CLONE_DEPTH: 3

  releaseJobSince:
    requires: [ ~release ]
    environment:
      GIT_SHALLOW_CLONE_SINCE: 2024-07-16

  tagJobSince:
    requires: [ ~tag ]
    environment:
      GIT_SHALLOW_CLONE_SINCE: 2024-07-16

  releaseJobShallowFalse:
    requires: [ ~release ]
    environment:
      GIT_SHALLOW_CLONE: false

  tagJobShallowFalse:
    requires: [ ~tag ]
    environment:
      GIT_SHALLOW_CLONE: false
